name: Release

on:
  pull_request:
    branches-ignore:
      - 'master'
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  release-to-pypi:
    runs-on: ubuntu-22.04
    environment: ci
    steps:
    - uses: actions/checkout@v3
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: 3.7
        cache: false
        prerelease: true

    - name: Publish wheels
      run: |
        pdm publish
      env:
        PDM_PUBLISH_USERNAME: chaostoolkit
        PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_PWD }}

    - name: Upload packages as artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: chaostoolkit-packages
        path: dist/chaostoolkit-*
